### ISSUE TITLE
FR4: Ability to remember username

### ISSUE THREAD

**Issue by McLow27** [WSU-4110/Dinners-Done#11]
|FR4. Ability to remember username |
|---|
|**Goal**: The login page will remember the last account username entered.
**Stakeholders:** Users|
| **Description:** When a user logs into his/her account, he/she will have the option to select “Remember Username” button. If selected, the site will save the last username entered. Upon user’s return, saved username will be automatically entered into Username box on login screen.   |
| **Origin:** Based on the initial project presentation and specification document, team members produced this description during the first meeting. |
| **Version:** 1.0  |
|**Date:** 05/27/2022
|  **Priority:** 4 |

**Comment by KKarnick** [comment]
This was planned for the front end work. It was never developed or addressed in any Sprint. It was initially given a low value for importance and planned for Sprint 3. However as the project structure was changed in the last week, it was not completed.
