### ISSUE TITLE
FR5: Ability to reset password 

### ISSUE THREAD

**Issue by McLow27** [WSU-4110/Dinners-Done#12]
|FR5. Ability to reset password |
|---|
|**Goal**: Ability to reset a forgotten password.
**Stakeholders:** Users|
| **Description:** If a user forgets his/her account password, he/she can select the “Forgot Password” option on the login interface and will then be redirected to the Reset Password page. This page will require the user to enter the email address associated with the account. If the information provided is valid, the system will send an email to that account with a link to reset the password.  |
| **Origin:** During a group meeting, members decided this would be an important inclusion in users’ lists of desired site attributes.|
| **Version:** 1.0  |
|**Date:** 05/26/2022
|  **Priority:** 4 |

**Comment by KKarnick** [comment]
The code for this requirement was developed and tested on Java. It was completed and functional on the back end, but never implemented on the front end. 
When the project changed structure in the last week to negate all Java coding and utilize only JavaScript, this function was not addressed by those coding backend at that time.
