### ISSUE TITLE
FR6. Ability of user to receive emails 

### ISSUE THREAD

**Issue by McLow27** [WSU-4110/Dinners-Done#13]
|FR6. Ability of user to receive emails |
|---|
|**Goal**: Option for users to allow emails from site
**Stakeholders:** Users, System admin, Advertising |
| **Description:** Users will have the option to allow/disallow system-generated emails. Users will be advised that correspondence from system can/will include the following: issues regarding his/her account, promotion of new and featured recipes, and regular newsletters from site.   |
| **Origin:** After discussing possible user-desired attributes and site promotion, team members agreed to add this functionality. |
| **Version:** 1.0  |
|**Date:** 05/30/2022
|  **Priority:** 5 |

**Comment by KKarnick** [comment]
This requirement was addressed and nearly completed (only required an email address devoted to the site) at the end of Sprint 2 by the assigned member. The user would receive an automatic email upon forgotten password at that time. Later functionality could have easily been added to mass email the user database list.
After the majority-vote in the last week to abandon all the completed Java coding and rewrite the entire project using JavaScript, this was never readdressed by those working the backend at that time.
