### ISSUE TITLE
FR9: User can duplicate recipes as needed 

### ISSUE THREAD

**Issue by McLow27** [WSU-4110/Dinners-Done#16]
|FR9. User can duplicate recipes as needed |
|---|
|**Goal**: The user will have the ability to select additional multiples of the current recipe.
**Stakeholders:** Customers|
| **Description:** The site’s recipe information includes how many people a recipe is meant to feed. The user can duplicate the amount of ingredients as many times needed to ensure the selection (and list of ingredients) will appropriately reflect the number of servings the user desires. |
| **Origin:** After discussing ways in which to make the site function well for families of any size, the team members agreed to this addition the day before the first presentation (5/24).|
| **Version:** 1.0  |
|**Date:** 05/24/2022
|  **Priority:** 3 |

**Comment by KKarnick** [comment]
This requirement had been addressed on the HTML page, but that was never linked to the actual code in Java. The Java code to search the database for the recipe and multiply each returned ingredient of that recipe by the duplicate number selected had been addressed in the Java code.
When the project was changed in the last week, this was not addressed by the original assignee. Assignments were changed prior to closing to reflect original developer on the front end.
