### ISSUE TITLE
FR10: Searchable ingredients  

### ISSUE THREAD

**Issue by McLow27** [WSU-4110/Dinners-Done#17]
|FR10. Searchable ingredients  |
|---|
|**Goal**: The user will be able to search the database for a particular ingredient (chicken, beef, etc.) and will be provided with only the recipes that include that ingredient.
**Stakeholders:** Users|
| **Description:** The user will be able to utilize a search bar to enter any ingredient. After entering the ingredient, the recipe list displayed will all include the searched ingredient. This will allow users to plan meals around a particular item.   |
| **Origin:** This functional ability was added following team member input during recent meeting.|
| **Version:** 1.0  |
|**Date:** 05/22/2022
|  **Priority:** 5 |

**Comment by KKarnick** [comment]
This requirement had never been addressed. Originally its low priority rating slated it for Sprint 3. After the majority-vote to change the project structure in the last week of the term, the requirement was never completed.
