### ISSUE TITLE
FR11: Ability to reset input fields 

### ISSUE THREAD

**Issue by McLow27** [WSU-4110/Dinners-Done#18]
|FR11: Ability to reset input fields |
|---|
|**Goal**: Goal: The website will allow users to reset all selected options, instead of unselecting them one by one.
**Stakeholders:** Users|
| **Description:** User will have the ability to select multiple recipes prior to selecting “Save.”  Should the user opt to restart any selection process, he/she will be able to click a “Reset” button. Selection of this button will reset all currently selected (unsaved) options, therefore not requiring the user to deselect them one by one. Following the reset the user may reselect his/her options as desired.  |
| **Origin:**  Our team members produced this option during a WhatsApp group discussion during the week of 5/22/2022.|
| **Version:** 1.0  |
|**Date:** 05/22/2022
|  **Priority:** 5 |

**Comment by KKarnick** [comment]
This was planned as a front-end assignment. As it had a low priority level, it was slated for Sprint 3.
There was no implementation before or after the project changed structure in the last week.

**Comment by KKarnick** [comment]
This was planned as a front-end assignment. As it had a low priority level, it was slated for Sprint 3.
There was no implementation before or after the project changed structure in the last week.
